Repository MSA-2025-1/msa-medical, pull requests merged in 2025-07, with the labels that each got.

#49 Member 모듈 개선
  frontend/src/util/endpoints.js
  server/src/main/java/com/emr/slgi/auth/controller/AuthController.java
  server/src/main/java/com/emr/slgi/common/dto/ListResponse.java
  server/src/main/java/com/emr/slgi/member/controller/DoctorController.java
  server/src/main/java/com/emr/slgi/member/controller/PatientController.java
  server/src/main/java/com/emr/slgi/member/controller/StaffController.java
  server/src/main/java/com/emr/slgi/member/dao/MemberDAO.java
  server/src/main/java/com/emr/slgi/member/dto/DoctorUuidName.java
  server/src/main/java/com/emr/slgi/member/dto/PatientRegisterDTO.java
  server/src/main/java/com/emr/slgi/member/dto/PatientSearchDTO.java
  server/src/main/java/com/emr/slgi/member/dto/PatientSummary.java
  server/src/main/java/com/emr/slgi/member/dto/StaffSummary.java
  server/src/main/java/com/emr/slgi/member/service/MemberService.java
  server/src/main/resources/mappers/member.xml
Labels: 회원, 기능 추가, 리팩토링

#52 의사 로그인시 목록 가져오도록 수정
  frontend/src/reception/util/reception.js
  frontend/src/stores/waitingListStore.js
  sql/CREATE_TB_RECEPTION.sql
Labels: 프론트엔드, 리팩토링, 대기 목록

#54 대기 리스트에서 버튼 누를시 환자 상태 변환 기능 및 진단 작성 로직 다시 재정의
  frontend/src/components/diagnosis/MedicalTreatment.vue
  frontend/src/components/diagnosis/Treatment.vue
  frontend/src/components/diagnosis/VisitHistory.vue
  frontend/src/reception/util/reception.js
  frontend/src/reception/views/WaitingList.vue
  frontend/src/shared/components/WaitingListPatientList.vue
  frontend/src/shared/components/WaitingStatus.vue
  frontend/src/util/endpoints.js
  frontend/src/util/stompMethod.js
  frontend/src/views/HomeView.vue
  frontend/src/views/staff/StaffMainView.vue
  server/src/main/java/com/emr/slgi/reception/controller/ReceptionController.java
  server/src/main/java/com/emr/slgi/reception/enums/ReceptionStatus.java
  server/src/main/java/com/emr/slgi/status/Status.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentController.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentDAO.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentService.java
  server/src/main/resources/mappers/treatment/treatment.xml
  sql/TB_STATUS_GROUP_INSERT.sql
  sql/TB_TREATMENT.sql
Labels: 기능 추가, 대기 목록, 상태전환

#56 환자 대기 목록 리팩토링 및 웹 소켓 부분과 병합 후 충돌 문제 해결
  frontend/src/reception/util/reception.js
  frontend/src/reception/views/WaitingList.vue
  frontend/src/reservation/util/reservation.js
  frontend/src/reservation/views/ReservationList.vue
  frontend/src/reservation/views/ReservationListByPatient.vue
  frontend/src/router/reservationRoutes.js
  frontend/src/shared/components/WaitingListPatientList.vue
  frontend/src/shared/components/WaitingStatus.vue
  frontend/src/stores/waitingListStore.js
  frontend/src/util/common.js
  frontend/src/util/endpoints.js
  server/src/main/java/com/emr/slgi/reception/controller/ReceptionController.java
  server/src/main/java/com/emr/slgi/reception/dao/ReceptionDAO.java
  server/src/main/java/com/emr/slgi/reception/dto/WaitingList.java
  server/src/main/java/com/emr/slgi/reception/enums/ReceptionMessage.java
  server/src/main/java/com/emr/slgi/reception/enums/ReceptionStatus.java
  server/src/main/java/com/emr/slgi/reception/service/ReceptionService.java
  server/src/main/java/com/emr/slgi/reception/typehandler/ReceptionStatusTypeHandler.java
  server/src/main/java/com/emr/slgi/reception/util/ReceptionErrorMessage.java
  server/src/main/java/com/emr/slgi/reception/vo/UpdateReceptionStatusForm.java
  server/src/main/java/com/emr/slgi/reservation/controller/ReservationController.java
  server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
  server/src/main/java/com/emr/slgi/reservation/dto/ReservationListByPatient.java
  server/src/main/java/com/emr/slgi/reservation/service/ReservationService.java
  server/src/main/java/com/emr/slgi/reservation/vo/ReservationCancelForm.java
  server/src/main/java/com/emr/slgi/util/ReservationErrorMessage.java
  server/src/main/java/com/emr/slgi/util/Validate.java
  server/src/main/resources/mappers/reception/reception.xml
  server/src/main/resources/mappers/reservation/reservation.xml
  server/src/main/resources/mappers/status/status.xml
Labels: 프론트엔드, 백엔드, 리팩토링, 대기 목록, 상태전환

#55 프로필 기능 추가
  frontend/src/components/home/layout/Header.vue
  frontend/src/patient/components/Profile.vue
  frontend/src/patient/components/RegisterForm.vue
  frontend/src/patient/components/UpdateProfileForm.vue
  frontend/src/patient/views/MyPageView.vue
  frontend/src/patient/views/RegisterView.vue
  frontend/src/patient/views/UpdateProfile.vue
  frontend/src/router/patientRoutes.js
  frontend/src/util/endpoints.js
  server/src/main/java/com/emr/slgi/member/controller/PatientController.java
  server/src/main/java/com/emr/slgi/member/dao/MemberDAO.java
  server/src/main/java/com/emr/slgi/member/dto/MemberProfile.java
  server/src/main/java/com/emr/slgi/member/dto/MemberProfileResponse.java
  server/src/main/java/com/emr/slgi/member/dto/UpdatePatientProfile.java
  server/src/main/java/com/emr/slgi/member/dto/UpdatePatientProfileRequest.java
  server/src/main/java/com/emr/slgi/member/service/MemberService.java
  server/src/main/resources/mappers/member.xml
Labels: 회원, 기능 추가

#57 액세스 토큰 재발급 함수 분리
  frontend/src/auth/renewAccessToken.js
  frontend/src/util/customFetch.js
Labels: 프론트엔드, 인증, 리팩토링

#61 상태전환 및 진료 작성 및 결재 상태 전환
  frontend/src/components/diagnosis/MedicalTreatment.vue
  frontend/src/components/diagnosis/VisitHistory.vue
  frontend/src/components/diagnosis/VisitHistoryDetail.vue
  frontend/src/reception/views/WaitingList.vue
  frontend/src/shared/components/WaitingListPatientList.vue
  frontend/src/util/endpoints.js
  server/src/main/java/com/emr/slgi/payment/PayMent.java
  server/src/main/java/com/emr/slgi/payment/PayMentDAO.java
  server/src/main/java/com/emr/slgi/reception/controller/ReceptionController.java
  server/src/main/java/com/emr/slgi/treatment/Treatment.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentController.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentDAO.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentService.java
  server/src/main/resources/mappers/payment/paymet.xml
  server/src/main/resources/mappers/treatment/treatment.xml
  sql/TB_TREATMENT.sql
  sql/create tb_payment.sql
Labels: 진료, 수정, 상태전환

#58 의료진의 환자 등록 기능 구현
  frontend/src/reception/views/AcceptPatientByStaff.vue
  frontend/src/router/index.js
  frontend/src/router/staffRoutes.js
  frontend/src/staff/util/StaffMessage.js
  frontend/src/util/RegexPattern.js
  frontend/src/util/common.js
  frontend/src/util/endpoints.js
  frontend/src/util/regex.js
  frontend/src/views/staff/RegPatientByStaff.vue
  frontend/src/views/staff/StaffMainView.vue
  server/src/main/java/com/emr/slgi/member/controller/PatientController.java
Labels: 프론트엔드, 기능 추가, 방문접수, 환자 등록, 의료진

#62 main.js 실행 시에 프로필 가져오기 에러 잡기
  frontend/src/main.js
Labels: 회원, 프론트엔드, 수정

#59 환자 이름으로 환자 정보 검색
  frontend/src/assets/search.png
  frontend/src/router/index.js
  frontend/src/router/staffRoutes.js
  frontend/src/util/endpoints.js
  frontend/src/views/staff/Search.vue
Labels: 프론트엔드, 기능 추가, 의료진, 검색

#75 기존 reservationRoutes 의 경로를 patientRoutes로 이동
  frontend/src/router/patientRoutes.js
  frontend/src/router/reservationRoutes.js
Labels: 예약, 프론트엔드, 수정

#77 디비 테이블 명 대문자로 수정
  server/src/main/resources/mappers/attachment/attachment.xml
  server/src/main/resources/mappers/chat/chatMessage.xml
  server/src/main/resources/mappers/chat/chatRead.xml
  server/src/main/resources/mappers/chat/chatroom.xml
  server/src/main/resources/mappers/diagnosis/diagnosis.xml
  server/src/main/resources/mappers/disease/disease.xml
  server/src/main/resources/mappers/medicine/medicine.xml
  server/src/main/resources/mappers/payment/paymet.xml
  server/src/main/resources/mappers/prescription/prescription.xml
  server/src/main/resources/mappers/treatment/treatment.xml
Labels: 백엔드, 수정

#78 parm 추가했습니다(이클립스 연결 문제)
  server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
Labels: 수정

#81 대기 목록 버그 수정
  frontend/src/reception/views/AcceptPatientByStaff.vue
  frontend/src/reception/views/WaitingList.vue
  frontend/src/util/successMessage.js
  mariadb/sql/01_CREATE_TB_QUERY.sql
  server/src/main/java/com/emr/slgi/reception/dto/ReceptionInfo.java
  server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
  server/src/main/java/com/emr/slgi/reservation/service/ReservationService.java
  server/src/main/resources/mappers/reception/reception.xml
Labels: 프론트엔드, 백엔드, 수정, 방문접수, 대기 목록

#82 검색 관련 기능 추가
  frontend/src/util/errorMessage.js
  frontend/src/views/staff/Search.vue
Labels: 프론트엔드, 기능 추가, 의료진, 검색

#84 리프레시 토큰 회전
  frontend/src/auth/renewAccessToken.js
  server/src/main/java/com/emr/slgi/auth/dto/AccessTokenResponse.java
  server/src/main/java/com/emr/slgi/auth/dto/TokenResponse.java
  server/src/main/java/com/emr/slgi/auth/service/AuthService.java
  server/src/main/java/com/emr/slgi/auth/service/RefreshTokenService.java
Labels: 백엔드, 기능 추가, 인증

#87 의료진 로그아웃 추가
  frontend/src/staff/components/StaffMenuBar.vue
Labels: 프론트엔드, 기능 추가, 의료진

#86 모달에서 일반 Vue 로 변경
  frontend/src/router/staffRoutes.js
  frontend/src/staff/components/StaffMenuBar.vue
  frontend/src/staff/layouts/StaffLayOut.vue
  frontend/src/staff/views/RegPatientByStaff.vue
Labels: 프론트엔드, 리팩토링, 환자 등록

#93 Member 모듈 컨트롤러, 서비스 테스트
  server/build.gradle
  server/src/test/java/com/emr/slgi/SlgiApplicationTests.java
  server/src/test/java/com/emr/slgi/controller/PatientControllerTest.java
  server/src/test/java/com/emr/slgi/service/MemberServiceTest.java
Labels: 테스트, 회원, 백엔드

#95 DevOps 및 CD
  .dockerignore
  .env.template
  .github/workflows/deployment.yml
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/src/staff/views/RegPatientByStaff.vue
  server/.dockerignore
  server/Dockerfile
Labels: DevOps, Docker Compose, Git Action, AWS

#96 환자 페이지 개선
  frontend/index.html
  frontend/public/favicon.ico
  frontend/src/assets/logo.png
  frontend/src/assets/logo.svg
  frontend/src/common/components/Loading.vue
  frontend/src/patient/components/LoginForm.vue
  frontend/src/patient/components/Profile.vue
  frontend/src/patient/components/RegisterForm.vue
  frontend/src/patient/components/UpdateProfileForm.vue
  frontend/src/patient/layouts/Header.vue
  frontend/src/router/patientRoutes.js
  frontend/src/util/RegexPattern.js
Labels: 프론트엔드, 기능 추가, 디자인, 환자

#101 스웨거 프록시 설정, 시큐리티 필터 제외 처리
  frontend/nginx.conf
  frontend/vite.config.js
  server/src/main/java/com/emr/slgi/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/emr/slgi/config/SecurityConfig.java
Labels: 문서 작업

#104 예약 등록 관련 라우터 수정
  frontend/src/staff/components/StaffMenuBar.vue
Labels: 예약, 프론트엔드, 수정, 환자

#109 의료진 네비게이션 가드 구현 및 예약 등록 시 라우트 수정
  frontend/src/reservation/util/reservation.js
  frontend/src/router/index.js
  frontend/src/router/staffRoutes.js
  frontend/src/shared/views/RegReservation.vue
  frontend/src/staff/views/AcceptPatientByStaff.vue
  frontend/src/util/common.js
  frontend/src/util/roles.js
Labels: 프론트엔드, 기능 추가, 의료진

#110 사이드 바 CSS 수정
  frontend/src/assets/css/ReservationListByStaff.css
  frontend/src/assets/css/StaffMenuBar.css
  frontend/src/assets/css/WaitingStatus.css
  frontend/src/assets/css/waitingreservaion.css
  frontend/src/reception/components/WaitingList.vue
  frontend/src/staff/components/StaffMenuBar.vue
Labels: 예약, 프론트엔드, 수정, 대기 목록, 디자인

#113 fix : css명 소문자
  frontend/src/assets/css/StaffMainView.css
  frontend/src/assets/css/VisitHistory.css
  frontend/src/assets/css/visitHistoryDetail.css
  frontend/src/components/chat/Alarm.vue
  frontend/src/components/chat/ChatCreate.vue
  frontend/src/components/chat/ChatRoom.vue
  frontend/src/components/chat/ChatRooms.vue
  frontend/src/components/diagnosis/Attachment.vue
  frontend/src/components/diagnosis/Disease.vue
  frontend/src/components/diagnosis/MedicalTreatment.vue
  frontend/src/components/diagnosis/Medicine.vue
  frontend/src/components/diagnosis/Treatment.vue
  frontend/src/components/diagnosis/VisitHistory.vue
  frontend/src/components/diagnosis/VisitHistoryDetail.vue
  frontend/src/components/payment/DiseaseDocument.vue
  frontend/src/components/payment/MedicineDocument.vue
  frontend/src/components/payment/Payment.vue
  frontend/src/components/payment/PaymentList.vue
  frontend/src/components/payment/PaymentWindow.vue
  frontend/src/staff/views/StaffMainView.vue
Labels: 수정

#115 대문자 수정
  frontend/src/components/diagnosis/VisitHistory.vue
Labels: 수정

#116 의료진 메인 Viewport 에 보이도록 임시 수정
  frontend/src/assets/css/StaffLayOut.css
Labels: 프론트엔드, 수정, 의료진, 디자인

#118 예약 완료 시 라우터 수정
  frontend/src/reservation/util/reservation.js
Labels: 예약, 프론트엔드, 리팩토링, 환자

#122 당일 대기 목록만 가져오도록 주석 해제
  server/src/main/resources/mappers/reception/reception.xml
  server/src/main/resources/mappers/reservation/reservation.xml
Labels: 예약, 백엔드, 대기 목록, 의료진

#123 css 파일에 payment 명 붙여주기
  frontend/src/assets/css/Payment.css
  frontend/src/util/endpoints.js
Labels: 수정

#128 공통 부분 컴포넌트화, 중복 체크 유효성 검사 수정
  frontend/src/common/components/Input.vue
  frontend/src/common/components/InvalidityMessage.vue
  frontend/src/common/components/Label.vue
  frontend/src/patient/components/RegisterForm.vue
  frontend/src/patient/components/SectionDivider.vue
  frontend/src/patient/components/Title.vue
  frontend/src/patient/components/UpdateProfileForm.vue
  frontend/src/patient/views/LoginView.vue
  frontend/src/patient/views/MyPageView.vue
  frontend/src/patient/views/RegisterView.vue
  frontend/src/patient/views/UpdateProfile.vue
Labels: 프론트엔드, 리팩토링, 환자

#131 전날 예약 상태 변경 및 슬롯 생성 프로시저
  .github/workflows/deployment.yml
  docker-compose.yml
  mariadb/procedure/call_reset_tb_slot_and_create_slots.sql
  mariadb/sh/runAutoProcedure.sh
  mariadb/sql/04_reset_tb_slot_and_create_slots.sql
Labels: 예약, 기능 추가, AWS

#127 환자페이지 프론트엔드 개선
  frontend/src/router/index.js
  frontend/src/router/patientRoutes.js
  frontend/src/router/staffRoutes.js
  frontend/src/util/customFetch.js
Labels: 프론트엔드, 기능 추가, 리팩토링

#133 서버 인증 모듈 개선
  mariadb/sql/01_CREATE_TB_QUERY.sql
  server/src/main/java/com/emr/slgi/auth/config/JwtConfig.java
  server/src/main/java/com/emr/slgi/auth/config/SecurityConfig.java
  server/src/main/java/com/emr/slgi/auth/config/SecurityConstants.java
  server/src/main/java/com/emr/slgi/auth/controller/AuthController.java
  server/src/main/java/com/emr/slgi/auth/dao/CredentialsDAO.java
  server/src/main/java/com/emr/slgi/auth/dto/CredentialsCreateParam.java
  server/src/main/java/com/emr/slgi/auth/dto/LoginDTO.java
  server/src/main/java/com/emr/slgi/auth/dto/LoginRequest.java
  server/src/main/java/com/emr/slgi/auth/dto/LoginResponse.java
  server/src/main/java/com/emr/slgi/auth/dto/LogoutRequest.java
  server/src/main/java/com/emr/slgi/auth/dto/RefreshTokenRequest.java
  server/src/main/java/com/emr/slgi/auth/dto/RegisterByPatientRequest.java
  server/src/main/java/com/emr/slgi/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/emr/slgi/auth/service/AccessTokenService.java
  server/src/main/java/com/emr/slgi/auth/service/AuthService.java
  server/src/main/java/com/emr/slgi/auth/service/CredentialsService.java
  server/src/main/java/com/emr/slgi/auth/service/RefreshTokenService.java
  server/src/main/java/com/emr/slgi/auth/util/JwtUtil.java
  server/src/main/java/com/emr/slgi/config/StompHandler.java
  server/src/main/java/com/emr/slgi/exception/GlobalExceptionHandler.java
  server/src/main/resources/mappers/credentials/credentials.xml
  server/src/main/resources/mappers/member/member.xml
Labels: 백엔드, 인증, 리팩토링

#138 예약 시 충돌 문제 긴급 수정
  server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
  server/src/main/java/com/emr/slgi/reservation/service/ReservationService.java
  server/src/main/resources/mappers/reservation/reservation.xml
Labels: 예약, 백엔드, 수정

#126 환경 변수 기반 이미지 처리
  .github/workflows/deployment.yml
  docker-compose.yml
  frontend/nginx.conf
  frontend/src/components/chat/ChatRoom.vue
  server/src/main/java/com/emr/slgi/attachment/AttachmentController.java
  server/src/main/java/com/emr/slgi/attachment/AttachmentService.java
  server/src/main/java/com/emr/slgi/chat/DAO/ChatMessageDAO.java
  server/src/main/java/com/emr/slgi/chat/service/ChatMessageService.java
  server/src/main/java/com/emr/slgi/chat/service/ChatService.java
  server/src/main/resources/application.yml
  server/src/main/resources/mappers/chat/chatMessage.xml
Labels: 설정

#137 CSS 수정
  frontend/src/assets/css/StaffMenuBar.css
  frontend/src/assets/css/waitingreservaion.css
  frontend/src/patient/views/RegReservationByPatient.vue
  frontend/src/patient/views/ReservationListByPatient.vue
  frontend/src/reservation/components/RegReservation.vue
  frontend/src/reservation/components/SelectReservationDate.vue
  frontend/src/reservation/util/reservation.js
  frontend/src/reservation/views/RegReservationByPatient.vue
  frontend/src/reservation/views/RegReservationByStaff.vue
  frontend/src/router/patientRoutes.js
  frontend/src/router/staffRoutes.js
  frontend/src/staff/components/StaffMenuBar.vue
  frontend/src/staff/views/RegReservationByStaff.vue
Labels: 프론트엔드, 수정, 디자인

#135 배포 조건 변경 및 Redis Volume 설정 변경
  .github/workflows/deployment.yml
  docker-compose.yml
  mariadb/Dockerfile
  redis/Dockerfile
Labels: DevOps, Git Action

#136 회원가입에 플레이스홀더 추가
  frontend/src/patient/components/RegisterForm.vue
Labels: 회원, 프론트엔드, 디자인

#139 Volume 경로 수정 및 배포 실행 조건 변경
  .github/workflows/deployment.yml
  docker-compose.yml
Labels: DevOps, Docker Compose, Git Action, AWS

#140 사용하지 않는 이미지와 컨테이너 정리 추가
  .github/workflows/deployment.yml
Labels: DevOps, Git Action

#143 docs : 로그아웃시 연결 해제
  frontend/src/auth/components/LogoutButton.vue
  frontend/src/util/stompMethod.js
Labels: stomp, webSocket

#144 API 응답 메세지 추가
  server/src/main/java/com/emr/slgi/auth/service/AuthService.java
  server/src/main/java/com/emr/slgi/exception/GlobalExceptionHandler.java
  server/src/main/java/com/emr/slgi/member/controller/PatientController.java
Labels: 백엔드, 수정

#147 README.md 작성
  README.md
Labels: 문서 작업

#148 .env.template 업데이트
  .env.template
Labels: 문서 작업
