Repository MSA-2025-1/msa-medical, pull requests merged in 2025-06, with the labels that each got.

#19 환자 직접 등록 기본 동작 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/util/common.js
  frontend/src/util/endpoints.js
  frontend/src/util/reservation.js
  frontend/src/views/regReservationByPatient.vue
  server/src/main/java/com/emr/slgi/doctor/DoctorController.java
  server/src/main/java/com/emr/slgi/member/ReservationForm.java
  server/src/main/java/com/emr/slgi/nurse/NurseController.java
  server/src/main/java/com/emr/slgi/reservation/PatientController.java
  server/src/main/java/com/emr/slgi/reservation/PatientService.java
  server/src/main/java/com/emr/slgi/reservation/controller/ReservationController.java
  server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
  server/src/main/java/com/emr/slgi/reservation/dto/FindReservationDate.java
  server/src/main/java/com/emr/slgi/reservation/dto/ReservationForm.java
  server/src/main/java/com/emr/slgi/reservation/dto/ReservationList.java
  server/src/main/java/com/emr/slgi/reservation/service/ReservationService.java
  server/src/main/java/com/emr/slgi/util/CommonErrorMessage.java
  server/src/main/java/com/emr/slgi/util/ReservationErrorMessage.java
  server/src/main/java/com/emr/slgi/util/Validate.java
  server/src/main/resources/mappers/patient.xml
  sql/CREATE TB_RESERVATION_TMP.sql
Labels: 예약

#14 실시간 채팅 기능들
  .gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/chat/login.vue
  frontend/src/stores/counter.js
  frontend/vite.config.js
  websocket/.gitattributes
  websocket/.gitignore
  websocket/build.gradle
  websocket/gradle/wrapper/gradle-wrapper.jar
  websocket/gradle/wrapper/gradle-wrapper.properties
  websocket/gradlew
  websocket/gradlew.bat
  websocket/settings.gradle
  websocket/src/main/java/com/emr/slgi/DAO/ChatJoinDAO.java
  websocket/src/main/java/com/emr/slgi/DAO/ChatMessageDAO.java
  websocket/src/main/java/com/emr/slgi/DAO/ChatReadDAO.java
  websocket/src/main/java/com/emr/slgi/DAO/ChatRoomDAO.java
  websocket/src/main/java/com/emr/slgi/DAO/MemberDAO.java
  websocket/src/main/java/com/emr/slgi/DTO/ChatAlarmDTO.java
  websocket/src/main/java/com/emr/slgi/DTO/ChatJoin.java
  websocket/src/main/java/com/emr/slgi/DTO/ChatMessage.java
  websocket/src/main/java/com/emr/slgi/DTO/ChatRead.java
  websocket/src/main/java/com/emr/slgi/DTO/ChatRoom.java
  websocket/src/main/java/com/emr/slgi/DTO/ChatRoomCreate.java
  websocket/src/main/java/com/emr/slgi/DTO/Member.java
  websocket/src/main/java/com/emr/slgi/WebsocketApplication.java
  websocket/src/main/java/com/emr/slgi/config/SecurityConfig.java
  websocket/src/main/java/com/emr/slgi/config/StompHandler.java
  websocket/src/main/java/com/emr/slgi/config/WebSocketConfig.java
  websocket/src/main/java/com/emr/slgi/controller/ChatController.java
  websocket/src/main/java/com/emr/slgi/controller/ChatJoinController.java
  websocket/src/main/java/com/emr/slgi/controller/ChatMessageController.java
  websocket/src/main/java/com/emr/slgi/controller/ChatReadController.java
  websocket/src/main/java/com/emr/slgi/controller/ChatRoomController.java
  websocket/src/main/java/com/emr/slgi/controller/MemberController.java
  websocket/src/main/java/com/emr/slgi/service/ChatJoinService.java
  websocket/src/main/java/com/emr/slgi/service/ChatMessageService.java
  websocket/src/main/java/com/emr/slgi/service/ChatReadService.java
  websocket/src/main/java/com/emr/slgi/service/ChatRoomService.java
  websocket/src/main/java/com/emr/slgi/service/MemberService.java
  websocket/src/main/resources/application.yml
  websocket/src/main/resources/mappers/chatJoin.xml
  websocket/src/main/resources/mappers/chatMessage.xml
  websocket/src/main/resources/mappers/chatRead.xml
  websocket/src/main/resources/mappers/chatroom.xml
  websocket/src/main/resources/mappers/member.xml
  websocket/src/test/java/com/emr/slgi/WebsocketApplicationTests.java
Labels: 실시간 채팅

#21 endpoint 부분 중복 문제 해결 및 patient 오타 수정
  frontend/src/util/endpoints.js
  frontend/src/views/regReservationByPatient.vue
Labels: 프론트엔드, 수정

#23 fix: 날짜 선택할 때마다 1시간씩 예약 시간 증가하는 버그 수정.
  frontend/src/router/index.js
  frontend/src/util/endpoints.js
  frontend/src/util/reservation.js
  frontend/src/views/regReservationByPatient.vue
Labels: 예약, 프론트엔드, 기능 추가, 수정

#27 refactor: LocalDateTime에서 OffsetDateTime으로 타입 변경함에 따라 관련 내용들 수정.
  frontend/src/util/common.js
  frontend/src/util/endpoints.js
  frontend/src/util/reservation.js
  frontend/src/views/reservation/RegReservationByPatient.vue
  server/src/main/java/com/emr/slgi/reservation/controller/ReservationController.java
  server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
  server/src/main/java/com/emr/slgi/reservation/dto/FindReservationDate.java
  server/src/main/java/com/emr/slgi/reservation/dto/ReservationForm.java
  server/src/main/java/com/emr/slgi/reservation/service/ReservationService.java
  server/src/main/resources/mappers/reservation.xml
Labels: 예약, 프론트엔드, 백엔드, 리팩토링

#28 feat: 의료진 방문 접수 관련 기본 동작 구현
  frontend/src/router/index.js
  frontend/src/util/endpoints.js
  frontend/src/util/regex.js
  frontend/src/views/reception/AcceptPatientByStaff.vue
  server/src/main/java/com/emr/slgi/reception/controller/ReceptionController.java
  server/src/main/java/com/emr/slgi/reception/dao/ReceptionDAO.java
  server/src/main/java/com/emr/slgi/reception/dto/ReceptionInfo.java
  server/src/main/java/com/emr/slgi/reception/service/ReceptionService.java
  server/src/main/java/com/emr/slgi/reception/service/WaitingList.java
  server/src/main/java/com/emr/slgi/util/ReceptionErrorMessage.java
  server/src/main/java/com/emr/slgi/util/Validate.java
  server/src/main/resources/mappers/reception.xml
  sql/CREATE_TB_RECEPTION.sql
  sql/TB_STATUS_GROUP_INSERT.sql
Labels: 프론트엔드, 백엔드, 기능 추가, 방문접수

#30 액세스 토큰을 사용한 로그인 기능
  frontend/src/auth/accessToken.js
  frontend/src/components/auth/LoginForm.vue
  frontend/src/components/home/layout/Header.vue
  frontend/src/router/index.js
  frontend/src/util/customFetch.js
  frontend/src/util/endpoints.js
  frontend/src/views/auth/LoginView.vue
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/emr/slgi/auth/AuthController.java
  server/src/main/java/com/emr/slgi/auth/AuthService.java
  server/src/main/java/com/emr/slgi/auth/dto/LoginDTO.java
  server/src/main/java/com/emr/slgi/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/emr/slgi/config/SecurityConfig.java
  server/src/main/java/com/emr/slgi/credentials/Credentials.java
  server/src/main/java/com/emr/slgi/credentials/CredentialsDAO.java
  server/src/main/java/com/emr/slgi/member/Member.java
  server/src/main/java/com/emr/slgi/member/MemberDAO.java
  server/src/main/java/com/emr/slgi/member/MemberService.java
  server/src/main/java/com/emr/slgi/member/enums/MemberRole.java
  server/src/main/java/com/emr/slgi/mybatis/typehandler/MemberRoleTypeHandler.java
  server/src/main/java/com/emr/slgi/util/JwtUtil.java
  server/src/main/resources/application.yml
  server/src/main/resources/mappers/credentials.xml
  server/src/main/resources/mappers/member.xml
Labels: 백엔드, 기능 추가, 인증

#31 ISO8601 형식으로 넘기는 타임존(Z) 정보를 가진 UTC 데이터를 전역으로 직렬화 / 역직렬화 수행.
  server/src/main/java/com/emr/slgi/config/DateTimeConverterConfig.java
  server/src/main/java/com/emr/slgi/config/JacksonDateTimeConfig.java
  server/src/main/java/com/emr/slgi/config/JacksonTimeZoneConverter.java
  server/src/main/java/com/emr/slgi/config/StringToKstLocalDateTimeConverter.java
Labels: 백엔드, 기능 추가

#32 예약 홀딩 기능 동작하도록 수정
  frontend/src/util/endpoints.js
  frontend/src/util/reservation.js
  frontend/src/views/reservation/RegReservationByPatient.vue
  server/src/main/java/com/emr/slgi/reservation/controller/ReservationController.java
  server/src/main/java/com/emr/slgi/reservation/dao/ReservationDAO.java
  server/src/main/java/com/emr/slgi/reservation/dto/FindReservationDate.java
  server/src/main/java/com/emr/slgi/reservation/dto/ReservationForm.java
  server/src/main/java/com/emr/slgi/reservation/dto/ReservationList.java
  server/src/main/java/com/emr/slgi/reservation/service/ReservationService.java
  server/src/main/java/com/emr/slgi/util/Validate.java
  server/src/main/resources/mappers/reservation.xml
Labels: 예약, 프론트엔드, 백엔드, 수정, 홀딩

#35 유저 프로필 가져오기
  frontend/src/App.vue
  frontend/src/components/auth/LoginForm.vue
  frontend/src/stores/userStore.js
  frontend/src/util/endpoints.js
  frontend/src/util/getMe.js
  server/src/main/java/com/emr/slgi/member/controller/MemberController.java
Labels: 회원, 기능 추가

#37 의료진용 환자 대기 리스트 기본 구현
  frontend/src/router/index.js
  frontend/src/router/receptionRoutes.js
  frontend/src/stores/waitingListStore.js
  frontend/src/util/endpoints.js
  frontend/src/util/errorMessage.js
  frontend/src/util/reception.js
  frontend/src/util/successMessage.js
  frontend/src/views/reception/Reception.vue
  frontend/src/views/reception/WaitingList.vue
  frontend/src/views/reception/WaitingListDoctorName.vue
  frontend/src/views/reception/WaitingListPatientList.vue
  server/src/main/java/com/emr/slgi/doctor/DoctorController.java
  server/src/main/java/com/emr/slgi/member/MemberDAO.java
  server/src/main/java/com/emr/slgi/member/MemberService.java
  server/src/main/java/com/emr/slgi/reception/controller/ReceptionController.java
  server/src/main/java/com/emr/slgi/reception/dao/ReceptionDAO.java
  server/src/main/java/com/emr/slgi/reception/service/ReceptionService.java
  server/src/main/java/com/emr/slgi/reception/service/WaitingList.java
  server/src/main/java/com/emr/slgi/util/ReceptionErrorMessage.java
  server/src/main/resources/mappers/member.xml
  server/src/main/resources/mappers/reception.xml
Labels: 프론트엔드, 백엔드, 기능 추가, 대기 목록

#36 진료 작성, 첨부파일, 이력확인, 약,질병 검색및 추가하기
  frontend/src/components/diagnosis/Attachment.vue
  frontend/src/components/diagnosis/Disease.vue
  frontend/src/components/diagnosis/MedicalTreatment.vue
  frontend/src/components/diagnosis/Medicine.vue
  frontend/src/components/diagnosis/Treatment.vue
  frontend/src/components/diagnosis/VisitHistory.vue
  frontend/src/components/diagnosis/VisitHistoryDetail.vue
  frontend/src/router/index.js
  frontend/src/util/endpoints.js
  server/src/main/java/com/emr/slgi/attachment/Attachment.java
  server/src/main/java/com/emr/slgi/attachment/AttachmentController.java
  server/src/main/java/com/emr/slgi/attachment/AttachmentDAO.java
  server/src/main/java/com/emr/slgi/attachment/AttachmentService.java
  server/src/main/java/com/emr/slgi/diagnosis/Diagnosis.java
  server/src/main/java/com/emr/slgi/diagnosis/DiagnosisDAO.java
  server/src/main/java/com/emr/slgi/disease/Disease.java
  server/src/main/java/com/emr/slgi/disease/DiseaseController.java
  server/src/main/java/com/emr/slgi/disease/DiseaseDAO.java
  server/src/main/java/com/emr/slgi/disease/DiseaseService.java
  server/src/main/java/com/emr/slgi/exception/GlobalExceptionHandler.java
  server/src/main/java/com/emr/slgi/medicine/Medicine.java
  server/src/main/java/com/emr/slgi/medicine/MedicineController.java
  server/src/main/java/com/emr/slgi/medicine/MedicineDAO.java
  server/src/main/java/com/emr/slgi/medicine/MedicineService.java
  server/src/main/java/com/emr/slgi/prescription/Prescription.java
  server/src/main/java/com/emr/slgi/prescription/PrescriptionDAO.java
  server/src/main/java/com/emr/slgi/treatment/TotalTreatmentDTO.java
  server/src/main/java/com/emr/slgi/treatment/Treatment.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentController.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentDAO.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentService.java
  server/src/main/resources/mappers/attachment/attachment.xml
  server/src/main/resources/mappers/diagnosis/diagnosis.xml
  server/src/main/resources/mappers/disease/disease.xml
  server/src/main/resources/mappers/medicine/medicine.xml
  server/src/main/resources/mappers/prescription/prescription.xml
  server/src/main/resources/mappers/treatment/treatment.xml
  sql/TB_ATTACHMENT.sql
  sql/TB_DIAGNOSIS.sql
  sql/TB_DISEASE.sql
  sql/TB_MEDICINE.sql
  sql/TB_PRESCRIPTION.sql
  sql/TB_TREATMENT.sql
Labels: 진료

#38 로그인 시 회원에 맞게 페이지 이동
  frontend/src/components/auth/LoginForm.vue
  frontend/src/router/adminRoutes.js
  frontend/src/router/index.js
  frontend/src/views/admin/AdminView.vue
Labels: 회원, 프론트엔드, 기능 추가

#39 사용하지 않는 import 제거
  frontend/src/router/receptionRoutes.js
Labels: 프론트엔드, 수정, 리팩토링

#41 접수 테이블 Mapper 초안 및 WaitingList.vue의 불필요한 import 때문에 발생한 에러 해결
  frontend/src/router/index.js
  frontend/src/views/reception/WaitingList.vue
  server/src/main/java/com/emr/slgi/reception/enums/ReceptionStatus.java
Labels: 프론트엔드, 백엔드, 수정, 대기 목록

#42 진료 내역 기록 페이징 기능 추가
  frontend/src/components/diagnosis/VisitHistory.vue
  frontend/src/util/endpoints.js
  server/src/main/java/com/emr/slgi/attachment/AttachmentController.java
  server/src/main/java/com/emr/slgi/page/PageDTO.java
  server/src/main/java/com/emr/slgi/page/PageResponseDTO.java
  server/src/main/java/com/emr/slgi/page/TreatmentHitoryRequestDTO.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentController.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentDAO.java
  server/src/main/java/com/emr/slgi/treatment/TreatmentService.java
  server/src/main/resources/mappers/treatment/treatment.xml
Labels: 진료

#43 로그아웃 기능 추가
  frontend/src/auth/accessToken.js
  frontend/src/auth/components/LogoutButton.vue
  frontend/src/auth/refreshToken.js
  frontend/src/components/home/layout/Header.vue
  frontend/src/util/endpoints.js
  server/build.gradle
  server/src/main/java/com/emr/slgi/auth/controller/AuthController.java
  server/src/main/java/com/emr/slgi/auth/dto/LogoutDTO.java
  server/src/main/java/com/emr/slgi/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/emr/slgi/auth/service/AuthService.java
  server/src/main/java/com/emr/slgi/auth/service/RefreshTokenService.java
  server/src/main/java/com/emr/slgi/util/JwtUtil.java
Labels: 기능 추가, 인증

#44 의료진용 대기 환자 목록 드롭다운 구현
  frontend/src/router/receptionRoutes.js
  frontend/src/stores/waitingListStore.js
  frontend/src/util/endpoints.js
  frontend/src/util/reception.js
  frontend/src/views/reception/WaitingList.vue
  frontend/src/views/reception/WaitingListPatientList.vue
  frontend/src/views/reception/WaitingStatus.vue
  server/src/main/java/com/emr/slgi/reception/controller/ReceptionController.java
  server/src/main/java/com/emr/slgi/reception/dao/ReceptionDAO.java
  server/src/main/java/com/emr/slgi/reception/dto/ReceptionStatusList.java
  server/src/main/java/com/emr/slgi/reception/dto/UpdateReceptionStatus.java
  server/src/main/java/com/emr/slgi/reception/dto/WaitingList.java
  server/src/main/java/com/emr/slgi/reception/enums/ReceptionStatus.java
  server/src/main/java/com/emr/slgi/reception/service/ReceptionService.java
  server/src/main/java/com/emr/slgi/reception/service/WaitingList.java
  server/src/main/java/com/emr/slgi/reception/typehandler/ReceptionStatusTypeHandler.java
  server/src/main/java/com/emr/slgi/util/CommonErrorMessage.java
  server/src/main/java/com/emr/slgi/util/ReceptionMessage.java
  server/src/main/resources/mappers/member.xml
  server/src/main/resources/mappers/reception.xml
  sql/CREATE_TB_RECEPTION.sql
Labels: 프론트엔드, 백엔드, 기능 추가, 방문접수, 대기 목록

#45 모듈 리팩토링
  server/src/main/java/com/emr/slgi/auth/dao/CredentialsDAO.java
  server/src/main/java/com/emr/slgi/auth/domain/Credentials.java
  server/src/main/java/com/emr/slgi/auth/dto/CredentialsCreateDTO.java
  server/src/main/java/com/emr/slgi/auth/service/AuthService.java
  server/src/main/java/com/emr/slgi/auth/service/CredentialsService.java
  server/src/main/java/com/emr/slgi/member/MemberService.java
  server/src/main/java/com/emr/slgi/member/controller/DoctorController.java
  server/src/main/java/com/emr/slgi/member/controller/MemberController.java
  server/src/main/java/com/emr/slgi/member/controller/PatientController.java
  server/src/main/java/com/emr/slgi/member/controller/StaffController.java
  server/src/main/java/com/emr/slgi/member/dao/MemberDAO.java
  server/src/main/java/com/emr/slgi/member/domain/Member.java
  server/src/main/java/com/emr/slgi/member/dto/PatientRegisterDTO.java
  server/src/main/java/com/emr/slgi/member/dto/PatientSearchDTO.java
  server/src/main/java/com/emr/slgi/member/service/MemberService.java
  server/src/main/java/com/emr/slgi/nurse/NurseController.java
  server/src/main/java/com/emr/slgi/patient/PatientService.java
  server/src/main/java/com/emr/slgi/staff/StaffService.java
  server/src/main/resources/mappers/credentials.xml
  server/src/main/resources/mappers/member.xml
Labels: 회원, 백엔드, 인증, 리팩토링
